channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=24.1.2
- pip:
  - mlflow==3.7.0
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==7.1.3
  - scikit-learn==1.2.2
  - scipy==1.15.3
  - xgboost==2.0.3
name: mlflow-env
