from typing import Optional, Union
from pydantic import BaseModel

Number = Union[float, int, None]

class PredictionRequest(BaseModel):
    D8: Number
    uid_M3_ct: Number
    uid_V_PCA_5_rel: Number
    uid_day_of_week_TransactionAmt_std: Number
    uid_C14_mean: Number
    uid_V_PCA_11_mean: Number
    uid_C11_rel: Number
    D10: Number
    uid_V_PCA_13_std: Number
    uid_DeviceType_freq: Number
    card6: Number
    D15: Number
    uid_C13_mean: Number
    uid_V_PCA_5_std: Number
    uid_V_PCA_7_rel: Number
    uid_C13_std: Number
    ProductCD_TransactionAmt_rel: Number
    id_19: Number
    uid_V_PCA_10_mean: Number
    card1: Number
    C1: Number
    uid_V_PCA_9_rel: Number
    uid_V_PCA_4_mean: Number
    id_18: Number
    uid_C12_rel: Number
    uid_id_30_ct: Number
    id_30: Number
    uid_V_PCA_3_std: Number
    P_emaildomain: Number
    D4: Number
    uid_id_31_ct: Number
    uid_DeviceInfo_ct: Number
    addr2: Number
    D14: Number
    uid_V_PCA_1_mean: Number
    V_PCA_13: Number
    C9: Number
    uid_TransactionAmt_rel: Number
    day_of_week: Number
    uid_M4_ct: Number
    C5: Number
    uid_V_PCA_13_mean: Number
    uid_V_PCA_7_mean: Number
    id_21: Number
    uid_C5_std: Number
    uid_V_PCA_5_mean: Number
    uid_V_PCA_3_rel: Number
    M1: Number
    uid_C7_rel: Number
    D13: Number
    uid_TransactionAmt_mean: Number
    M4: Number
    uid_C9_std: Number
    uid_C14_rel: Number
    id_38: Number
    V_PCA_10: Number
    ProductCD_TransactionAmt_mean: Number
    uid_V_PCA_12_rel: Number
    V_PCA_2: Number
    M6: Number
    D7: Number
    uid_V_PCA_8_mean: Number
    uid_C3_mean: Number
    uid_M9_ct: Number
    DecimalPlaces: Number
    uid_V_PCA_8_std: Number
    V_PCA_12: Number
    uid_V_PCA_2_rel: Number
    uid_V_PCA_6_mean: Number
    card4: Number
    id_05: Number
    id_15: Number
    D9: Number
    uid_TransactionAmt_std: Number
    id_02: Number
    R_emaildomain: Number
    addr1: Number
    V_PCA_8: Number
    DeviceType: Number
    uid_C7_std: Number
    id_07: Number
