from typing import Optional, Union
from pydantic import BaseModel

Number = Union[float, int, None]
FeatureValue = Union[float, int, str, None]

class PredictionRequest(BaseModel):
    D8: FeatureValue
    uid_M3_ct: FeatureValue
    uid_V_PCA_5_rel: FeatureValue
    uid_day_of_week_TransactionAmt_std: FeatureValue
    uid_C14_mean: FeatureValue
    uid_V_PCA_11_mean: FeatureValue
    uid_C11_rel: FeatureValue
    D10: FeatureValue
    uid_V_PCA_13_std: FeatureValue
    uid_DeviceType_freq: FeatureValue
    card6: FeatureValue
    D15: FeatureValue
    uid_C13_mean: FeatureValue
    uid_V_PCA_5_std: FeatureValue
    uid_V_PCA_7_rel: FeatureValue
    uid_C13_std: FeatureValue
    ProductCD_TransactionAmt_rel: FeatureValue
    id_19: FeatureValue
    uid_V_PCA_10_mean: FeatureValue
    card1: FeatureValue
    C1: FeatureValue
    uid_V_PCA_9_rel: FeatureValue
    uid_V_PCA_4_mean: FeatureValue
    id_18: FeatureValue
    uid_C12_rel: FeatureValue
    uid_id_30_ct: FeatureValue
    id_30: FeatureValue
    uid_V_PCA_3_std: FeatureValue
    P_emaildomain: FeatureValue
    D4: FeatureValue
    uid_id_31_ct: FeatureValue
    uid_DeviceInfo_ct: FeatureValue
    addr2: FeatureValue
    D14: FeatureValue
    uid_V_PCA_1_mean: FeatureValue
    V_PCA_13: FeatureValue
    C9: FeatureValue
    uid_TransactionAmt_rel: FeatureValue
    day_of_week: FeatureValue
    uid_M4_ct: FeatureValue
    C5: FeatureValue
    uid_V_PCA_13_mean: FeatureValue
    uid_V_PCA_7_mean: FeatureValue
    id_21: FeatureValue
    uid_C5_std: FeatureValue
    uid_V_PCA_5_mean: FeatureValue
    uid_V_PCA_3_rel: FeatureValue
    M1: FeatureValue
    uid_C7_rel: FeatureValue
    D13: FeatureValue
    uid_TransactionAmt_mean: FeatureValue
    M4: FeatureValue
    uid_C9_std: FeatureValue
    uid_C14_rel: FeatureValue
    id_38: FeatureValue
    V_PCA_10: FeatureValue
    ProductCD_TransactionAmt_mean: FeatureValue
    uid_V_PCA_12_rel: FeatureValue
    V_PCA_2: FeatureValue
    M6: FeatureValue
    D7: FeatureValue
    uid_V_PCA_8_mean: FeatureValue
    uid_C3_mean: FeatureValue
    uid_M9_ct: FeatureValue
    DecimalPlaces: FeatureValue
    uid_V_PCA_8_std: FeatureValue
    V_PCA_12: FeatureValue
    uid_V_PCA_2_rel: FeatureValue
    uid_V_PCA_6_mean: FeatureValue
    card4: FeatureValue
    id_05: FeatureValue
    id_15: FeatureValue
    D9: FeatureValue
    uid_TransactionAmt_std: FeatureValue
    id_02: FeatureValue
    R_emaildomain: FeatureValue
    addr1: FeatureValue
    V_PCA_8: FeatureValue
    DeviceType: FeatureValue
    uid_C7_std: FeatureValue
    id_07: FeatureValue
