artifact_uri: /kaggle/working/mlruns/799800133761451759/1fccdcb909ac4dbbab68367ce7eeacb0/artifacts
end_time: 1765122684432
entry_point_name: ''
experiment_id: '799800133761451759'
lifecycle_stage: active
run_id: 1fccdcb909ac4dbbab68367ce7eeacb0
run_name: XGB_Reduced
source_name: ''
source_type: 4
source_version: ''
start_time: 1765122662206
status: 3
tags: []
user_id: root
